#
# Import necessary Python libraries
#
import re

#
# VARIABLES - USER, PLEASE SET THESE YOURSELF!
#
# The path to file list should be a list of files generated by
# FASTQC named fastqc_data.txt; they are generally found in the
# ZIP file created when running FASTQC on the command line.
# 
# The threshold is the read quality score threshold that will be used. If/when the average
# quality for the file falls below the threshold, the script will output the current read length
# and then quit.
#
path_to_file_list = "/home/biocore/kdempsey/elgamal/progression_model/fastqc_data_files.list"
threshold = 28
#path_to_file_list = "/home/biocore/kdempsey/elgamal/adaptive_model/fastqc_data_files.list"
file_list = open(path_to_file_list,"r")

#
# Go through the list of fastqc data files and open each one, then
# you want to pull out the "Per Base Sequence Quality Section", which lists
# the Base #, Mean, Median, and Quartile/Percentile Quality Scores for the 
# reads in that fastq file. You can change the threshold used for quality 
# score by changing the threshold variable on line 14
# For more info: https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/QualityScoreEncoding_swBS.ht
for filename in file_list:
 f = open(filename.rstrip(), "r")
 line = f.readline()
 capture = False
 while line:
   if capture == True:
     columns = line.split('\t')
     base = columns[0]
     mean = float(columns[1])
     if(mean <= threshold):
         print(base)
         break
   if re.match("#Base",line):
     capture = True
   if re.match(">>END_MODULE",line):
     capture = False
   line = f.readline()
